name: Run Website Monitor

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  schedule:
    - cron: "*/15 * * * *"  # Runs every 5 minutes

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9  # Use the appropriate Python version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run monitor script
      env:
        TG_CHAT_ID: "7862790706"
        RECIPIENT_EMAIL: "rzk.rud@gmail.com"
        BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}  # Pass API key from GitHub Secrets
        TG_API_KEY: ${{ secrets.TG_API_KEY }}
      run: |
        python monitor_evzo_websites.py